### PR TITLE
(#320) Fix ''Build of whole project is broken."

### LINKED ISSUE #320: Build of whole project is broken.
Using command from README.md:
```
mvn clean install -Pqulice
```

I tried to build repo on my local machine (Windows 10) and it failed with:
```
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.8:check (jacoco-check) @ jpeek ---
[INFO] Loading execution data file C:\Users\Nikita_Puzankov\workspace\personal\jpeek\target\jacoco.exec
[INFO] Analyzed bundle 'jpeek' with 35 classes
[WARNING] Rule violated for bundle jpeek: lines covered ratio is 0.65, but expected minimum is 0.67
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:58 min
[INFO] Finished at: 2019-04-19T22:13:29+04:00
[INFO] Final Memory: 33M/329M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.8:check (jacoco-check) on project jpeek: Coverage checks have not been met. See log for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
**Without any local changes.**

I would like to see working build to work on the project instead of covering code with tests for free :-)

### PR DESCRIPTION
**Pull request by humb1t**
Lines covered ratio increased to 0.67.

- Fixes #320
- DyNumTest.java and PagesTest.java added to increase lines covered ratio

### CODE REVIEW

**Comment by humb1t** [comment]
@paulodamaso this PR contains commits from the fix of #268 because there was a test which also increased lines covered ratio.

**Comment by 0crat** [comment]
Job [#321](https://github.com/yegor256/jpeek/issues/321) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#321` already assigned to @ilyakharlamov, can't assign to @ilyakharlamov

**Comment by 0crat** [comment]
This pull request [#321](https://github.com/yegor256/jpeek/issues/321) is assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/db4e70a9-bbab-4b58-9d0f-46f93ad05416); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

File: src/test/java/org/jpeek/MainTest.java [hunk 1]
```diff
@@ -67,6 +67,27 @@ public void crashesIfNoOverwriteAndTargetExists() throws IOException {
         );
     }
 
+    @Test(expected = IllegalArgumentException.class)
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/MainTest.java]: use JUnit5-compatible, OO assertions 
 `new Assertion<>(
            "my text here",
            () -> {
                Main.main(
                    "--sources", Paths.get(".").toString(),
                    "--target", target.toString()
                );
                return null;
            },
            new Throws<>("must throw an exception", IllegalStateException.class)
        ).affirm();`

File: src/test/java/org/jpeek/MainTest.java [hunk 2]
```diff
@@ -67,6 +67,27 @@ public void crashesIfNoOverwriteAndTargetExists() throws IOException {
...
+        final Path source = Files.createTempDirectory("sourceequalstarget");
+        final Path target = source;
+        Main.main(
+            "--sources", source.toString(),
+            "--target", target.toString(),
+            "--overwrite"
+        );
+    }
+
+    @Test(expected = IllegalArgumentException.class)
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/MainTest.java]: use `new Assertion` + `new Throws`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+ */
+public final class DyNumTest {
+
+    @Test
+    public void testConstructDyNumFromString() {
+        final double number = 2.0f;
+        final DyNum dynum = new DyNum(
+            String.valueOf(number)
+        );
+        MatcherAssert.assertThat(
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: new Assertion<>().affirm

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+            dynum.doubleValue(),
+            Matchers.equalTo(number)
+        );
+    }
+
+    @Test
+    public void testConstructDyNumFromLong() {
+        final Long number = Long.valueOf(2);
+        final DyNum dynum = new DyNum(number);
+        MatcherAssert.assertThat(
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `new Assertion<>()`, `new IsEqual()`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+        );
+    }
+
+    @Test
+    public void testConstructDyNumFromLongCompareToFloat() {
+        final Float number = Float.valueOf(2);
+        final DyNum dynum = new DyNum(number);
+        MatcherAssert.assertThat(
+            dynum.floatValue(),
+            Matchers.equalTo(number.floatValue())
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `new Assertion<>(), new IsEqual()`

File: src/test/java/org/jpeek/web/PagesTest.java [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+ * @checkstyle JavadocMethodCheck (500 lines)
+ */
+public final class PagesTest {
+
+    @Test
+    public void testApply() throws IOException {
+        final Path temp = Files.createTempDirectory("");
+        temp.resolve("a/b/c").toFile().mkdirs();
+        final String path = "a/z.class";
+        Files.write(
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/PagesTest.java]: use `new org.cactoos.io.WriterTo` and, probably `org.cactoos.io.TempFile`. The general rule of these projects are `as few static methods as possible`, [see more](https://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html)

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+            dynum.doubleValue(),
+            Matchers.equalTo(number)
+        );
+    }
+
+    @Test
+    public void testUpdateDyNum() {
+        final Double number = Double.valueOf(2);
+        final DyNum dynum = new DyNum(number);
+        MatcherAssert.assertThat(
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `new Assertion().affirm()`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+            dynum.floatValue(),
+            Matchers.equalTo(number.floatValue())
+        );
+    }
+
+    @Test
+    public void testConstructDyNumFromDouble() {
+        final Double number = Double.valueOf(2);
+        final DyNum dynum = new DyNum(number);
+        MatcherAssert.assertThat(
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `new Assertion().affirm()`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+            dynum.floatValue(),
+            Matchers.equalTo(number.floatValue())
+        );
+    }
+
+    @Test
+    public void testConstructDyNumFromDouble() {
+        final Double number = Double.valueOf(2);
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: on line 41 you use `final double number = 2.0f;` 
but here you use `final Double number = Double.valueOf(2)` for the same value.
You'd better keep the same consistent style.

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+        final DyNum dynum = new DyNum(number);
+        MatcherAssert.assertThat(
+            dynum.longValue(),
+            Matchers.equalTo(number.longValue())
+        );
+    }
+
+    @Test
+    public void testConstructDyNumFromLongCompareToInt() {
+        final Double number = Double.valueOf(2);
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: either `new Double` or `2.0d`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 11]
```diff
@@ -0,0 +1,100 @@
...
+        );
+        MatcherAssert.assertThat(
+            dynum.doubleValue(),
+            Matchers.equalTo(number)
+        );
+    }
+
+    @Test
+    public void testConstructDyNumFromLong() {
+        final Long number = Long.valueOf(2);
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: either `final Long number = 2L`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 12]
```diff
@@ -0,0 +1,100 @@
...
+ * @author Nikita Puzankov (humb1t@yandex.ru)
+ * @version $Id$
+ * @since 0.31
+ * @checkstyle JavadocMethodCheck (500 lines)
+ */
+public final class DyNumTest {
+
+    @Test
+    public void testConstructDyNumFromString() {
+        final double number = 2.0f;
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `2.0d`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 13]
```diff
@@ -0,0 +1,100 @@
...
+        );
+    }
+
+    @Test
+    public void testConstructDyNumFromLong() {
+        final Long number = Long.valueOf(2);
+        final DyNum dynum = new DyNum(number);
+        MatcherAssert.assertThat(
+            dynum.longValue(),
+            Matchers.equalTo(number.longValue())
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: unnecessary unboxing, `number` is `Long` isn't it ?

File: src/main/java/org/jpeek/Main.java [hunk 14]
```diff
@@ -125,12 +125,31 @@ public static void main(final String... args) throws IOException {
...
+                this.target,
+                this.overwrite
+            ).toPath(),
+            params
+        ).analyze();
         if (!this.quiet) {
-            console.setLayout(new PatternLayout("%m%n"));
-            console.activateOptions();
-            Logger.getRootLogger().addAppender(console);
+            Logger.getRootLogger().removeAppender(console);
```
[the remark this answers is not in the document]
Comment (humb1t) [reply src/main/java/org/jpeek/Main.java]: @ilyakharlamov this code was just moved, not changed - are you sure we could change it to opposite?)

File: src/test/java/org/jpeek/MainTest.java (hunk 1 above)
Comment (humb1t) [reply src/test/java/org/jpeek/MainTest.java]: @ilyakharlamov ty, will fix it and also reported #323 to prevent this in future PRs

Comment (ilyakharlamov) [reply src/test/java/org/jpeek/MainTest.java]: I see you wrapped `buildConsoleAppender` and `buildParameters`, which is probably a good thing.
However there is still this raw `if (!this.quiet) {
            Logger.getRootLogger().removeAppender(console);
        }` which doesn not look right. Something needs to be changed here.

Comment (humb1t) [reply src/test/java/org/jpeek/MainTest.java]: image
image
As you can see - `addAppender` was in the start of a `run` method, now it's the same but inside `buildConsoleAppender` method - while `removeAppender` in the end of the `run` method stays where it was. It's out of scope of my PR to work with it or think about it.

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 15]
```diff
@@ -38,63 +40,71 @@
...
         final DyNum dynum = new DyNum(
             String.valueOf(number)
         );
-        MatcherAssert.assertThat(
-            dynum.doubleValue(),
-            Matchers.equalTo(number)
-        );
+        new Assertion<>(
+            "Double values should be equal",
+            () -> dynum.doubleValue(),
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: lambda can be replaced with method reference, `dynum::doubleValue` here

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 16]
```diff
@@ -38,63 +40,71 @@
...
-        final Long number = Long.valueOf(2);
+        final Long number = 2L;
         final DyNum dynum = new DyNum(number);
-        MatcherAssert.assertThat(
-            dynum.longValue(),
-            Matchers.equalTo(number.longValue())
-        );
+        new Assertion<>(
+            "Long values should be equal",
+            () -> dynum.longValue(),
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `dynum::longValue`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 17]
```diff
@@ -38,63 +40,71 @@
...
-        final Double number = Double.valueOf(2);
+        final Double number = 2.0d;
         final DyNum dynum = new DyNum(number);
-        MatcherAssert.assertThat(
-            dynum.intValue(),
-            Matchers.equalTo(number.intValue())
-        );
+        new Assertion<>(
+            "Integer values should be equal",
+            () -> dynum.intValue(),
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: no lambda, just method reference `dynum::intValue`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 18]
```diff
@@ -38,63 +40,71 @@
...
-        final Float number = Float.valueOf(2);
+        final Float number = 2.0f;
         final DyNum dynum = new DyNum(number);
-        MatcherAssert.assertThat(
-            dynum.floatValue(),
-            Matchers.equalTo(number.floatValue())
-        );
+        new Assertion<>(
+            "Float values should be equal",
+            () -> dynum.floatValue(),
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: same as above

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 19]
```diff
@@ -38,63 +40,71 @@
...
-        final Double number = Double.valueOf(2);
+        final Double number = 2.0d;
         final DyNum dynum = new DyNum(number);
-        MatcherAssert.assertThat(
-            dynum.doubleValue(),
-            Matchers.equalTo(number)
-        );
+        new Assertion<>(
+            "Double values should be equal.",
+            () -> dynum.doubleValue(),
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: same as above, method reference

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 20]
```diff
@@ -38,63 +40,71 @@
...
-        final Double number = Double.valueOf(2);
+        final Double number = 2.0d;
         final DyNum dynum = new DyNum(number);
-        MatcherAssert.assertThat(
-            dynum.update(),
-            Matchers.notNullValue()
-        );
+        new Assertion<>(
+            "Result should not be null",
+            () -> dynum.update(),
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: lambda can be replaced with method reference here

**Comment by ilyakharlamov** [comment]
@humb1t 
1. In DyNumTest, replace the lambdas with method references, remove all the unboxings number.floatValue, number.longValue, number.intValue etc
after that you will no longer need single-use variables like `final Double number` and `final DyNum dynum` you can inline that into, for example `testUpdateDyNum() {
        new Assertion<>(
            "Result should not be null",
            new DyNum(2.0d)::update,
            new IsNot<>(
                new IsNull<>()
            )
        ).affirm();
    }`

File: src/test/java/org/jpeek/MainTest.java (hunk 1 above)
Comment (ilyakharlamov) [reply src/test/java/org/jpeek/MainTest.java]: I don't see much of improvement in run() method here -  yes, the method became smaller but if (this.quiet) check is now scattered across different methods. You you can rollback `buildConsoleAppender` back if you don't feel like refactoring it.

Comment (humb1t) [reply src/test/java/org/jpeek/MainTest.java]: I can't because it's a statically analyze violation of a big complexity in one method, that's why I made these two methods. I think it was a mistake in the initial design. And the only thing I can do in this issue is a new private method and rename `buildConsoleAppender` into `construct` and the new one would be `destruct`

@paulodamaso  - what do you think?

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 21]
```diff
@@ -90,18 +90,16 @@ public void testConstructDyNumFromDouble() {
         final DyNum dynum = new DyNum(number);
         new Assertion<>(
             "Double values should be equal.",
-            () -> dynum.doubleValue(),
+            dynum::doubleValue,
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: get rid of intermediate dynum and number variables here
just `new DyNum(2.0f)::floatValue` etc

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 22]
```diff
@@ -46,7 +46,7 @@ public void testConstructDyNumFromString() {
         );
         new Assertion<>(
             "Double values should be equal",
-            () -> dynum.doubleValue(),
+            dynum::doubleValue,
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `new DyNum(2.0d)::doubleValue`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 23]
```diff
@@ -68,7 +68,7 @@ public void testConstructDyNumFromLongCompareToInt() {
         final DyNum dynum = new DyNum(number);
         new Assertion<>(
             "Integer values should be equal",
-            () -> dynum.intValue(),
+            dynum::intValue,
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: `new DyNum(2L)::intValue`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 24]
```diff
@@ -79,7 +79,7 @@ public void testConstructDyNumFromLongCompareToFloat() {
         final DyNum dynum = new DyNum(number);
         new Assertion<>(
             "Float values should be equal",
-            () -> dynum.floatValue(),
+            dynum::floatValue,
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: same as above

Comment (humb1t) [reply src/test/java/org/jpeek/web/DyNumTest.java]: got it

File: src/test/java/org/jpeek/web/DyNumTest.java (hunk 21 above)
Comment (humb1t) [reply src/test/java/org/jpeek/web/DyNumTest.java]: I didn't pass 2.0f and stayed with `number` because of later comparison with this value and static checks for duplicates of literals and numbers.

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 25]
```diff
@@ -41,56 +41,51 @@
...
 
     @Test
     public void testConstructDyNumFromLongCompareToFloat() {
         final Float number = 2.0f;
-        final DyNum dynum = new DyNum(number);
         new Assertion<>(
             "Float values should be equal",
-            dynum::floatValue,
+            new DyNum(number)::floatValue,
             new IsEqual<>(number.floatValue())
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: no need for unboxing here, just number

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 26]
```diff
@@ -41,56 +41,51 @@
...
             "Integer values should be equal",
-            dynum::intValue,
+            new DyNum(number)::intValue,
             new IsEqual<>(number.intValue())
         ).affirm();
     }
 
     @Test
     public void testConstructDyNumFromLongCompareToFloat() {
         final Float number = 2.0f;
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: can be primitive, just`float`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 27]
```diff
@@ -41,56 +41,51 @@
...
+            new DyNum(
+                String.valueOf(number)
+            )::doubleValue,
             new IsEqual<>(number)
         ).affirm();
     }
 
     @Test
     public void testConstructDyNumFromLong() {
         final Long number = 2L;
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: can be primitive, just `long`

File: src/test/java/org/jpeek/web/DyNumTest.java [hunk 28]
```diff
@@ -41,56 +41,51 @@
...
             "Float values should be equal",
-            dynum::floatValue,
+            new DyNum(number)::floatValue,
             new IsEqual<>(number.floatValue())
         ).affirm();
     }
 
     @Test
     public void testConstructDyNumFromDouble() {
         final Double number = 2.0d;
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/DyNumTest.java]: just `double`

**Comment by ilyakharlamov** [comment]
@humb1t fix We are close, just four DyNumTest changes + PagesTest

File: src/test/java/org/jpeek/web/DyNumTest.java (hunk 21 above)
Comment (ilyakharlamov) [reply src/test/java/org/jpeek/web/DyNumTest.java]: Ok, that's fine

File: src/test/java/org/jpeek/web/DyNumTest.java (hunk 25 above)
Comment (humb1t) [reply src/test/java/org/jpeek/web/DyNumTest.java]: It's needed to cover these lines in LoC limit. This issue is about this tech debt of the project and strange behaviour when commit without code changes can drop the LoC limit below configured 0.67.

File: src/test/java/org/jpeek/web/DyNumTest.java (hunk 26 above)
Comment (humb1t) [reply src/test/java/org/jpeek/web/DyNumTest.java]: It's needed to cover these lines in LoC limit. This issue is about this tech debt of the project and strange behaviour when commit without code changes can drop the LoC limit below configured 0.67.

File: src/test/java/org/jpeek/web/DyNumTest.java (hunk 27 above)
Comment (humb1t) [reply src/test/java/org/jpeek/web/DyNumTest.java]: It's needed to cover these lines in LoC limit. This issue is about this tech debt of the project and strange behaviour when commit without code changes can drop the LoC limit below configured 0.67.

File: src/test/java/org/jpeek/web/DyNumTest.java (hunk 28 above)
Comment (humb1t) [reply src/test/java/org/jpeek/web/DyNumTest.java]: It's needed to cover these lines in LoC limit. This issue is about this tech debt of the project and strange behaviour when commit without code changes can drop the LoC limit below configured 0.67.

File: src/test/java/org/jpeek/web/DyNumTest.java (hunk 25 above)
Comment (humb1t) [reply src/test/java/org/jpeek/web/DyNumTest.java]: sry - I thought about dynum, not a number. Will fix tommorow

**Comment by ilyakharlamov** [comment]
@humb1t 
fix the broken test, change PagesTest and rebase into a single nice looking commit and we are good to go

**Comment by humb1t** [comment]
@rultor help

**Comment by humb1t** [comment]
I will try to retrigger the build by amending the commit.

**Comment by humb1t** [comment]
@ilyakharlamov please check one more time :-)

File: src/test/java/org/jpeek/web/PagesTest.java [hunk 29]
```diff
@@ -0,0 +1,52 @@
...
+import org.junit.Test;
+
+/**
+ * Test case for {@link Pages}.
+ * @author Nikita Puzankov (humb1t@yandex.ru)
+ * @version $Id$
+ * @since 0.31
+ * @checkstyle JavadocMethodCheck (500 lines)
+ */
+public final class PagesTest {
```
Comment (ilyakharlamov) [inline src/test/java/org/jpeek/web/PagesTest.java]: What does this file test? 
I don't see any assertions.

Comment (humb1t) [reply src/test/java/org/jpeek/web/PagesTest.java]: It tests that `apply` wouldn't fail and it was written as all other tests just to increase LoC limit.

**Comment by ilyakharlamov** [comment]
@humb1t rebase all the changes into a single commit and we are good to go

**Comment by humb1t** [comment]
@ilyakharlamov I made a `todo` about tests without assertions and squashed commits into one.

**Comment by ilyakharlamov** [comment]
@paulodamaso the PR is OK, the only thing I am not sure of is PagesTest.

**Comment by humb1t** [comment]
@paulodamaso please check this PR, there are some issues blocked by it.

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by humb1t** [comment]
@paulodamaso please check this PR, there are some issues blocked by it.

**Comment by humb1t** [comment]
@paulodamaso the time has come :-)

File: src/test/java/org/jpeek/MainTest.java [hunk 30]
```diff
@@ -67,6 +69,47 @@ public void crashesIfNoOverwriteAndTargetExists() throws IOException {
...
+        final Path target = source;
+        new Assertion<>(
+            "Must throw an exception",
+            () -> {
+                Main.main(
+                    "--sources", source.toString(),
+                    "--target", target.toString(),
+                    "--overwrite"
+                );
+                return null;
```
Comment (paulodamaso) [inline src/test/java/org/jpeek/MainTest.java]: @humb1t Let's remove this null from here, I know that this method won't ever be called but it is still a bad pratice.

File: src/test/java/org/jpeek/MainTest.java [hunk 31]
```diff
@@ -67,6 +69,47 @@ public void crashesIfNoOverwriteAndTargetExists() throws IOException {
...
+        final Path target = Files.createTempDirectory("");
+        new Assertion<>(
+        "Must throw an exception",
+            () -> {
+                Main.main(
+                    "--sources", Paths.get(".").toString(),
+                    "--target", target.toString(),
+                    "--metrics", "#%$!"
+                );
+                return null;
```
Comment (paulodamaso) [inline src/test/java/org/jpeek/MainTest.java]: @humb1t Here too

File: src/test/java/org/jpeek/web/PagesTest.java [hunk 32]
```diff
@@ -0,0 +1,58 @@
...
+
+    /**
+     * Simple test.
+     * @todo The current solution to simply call an {@link Pages#apply(String)}
+     *  method and increase LoC coverage to pass 0.67 limit.
+     *  Refactor towards normal test with assertions and checks.
+     */
+    @Test
+    public void testApply() throws IOException {
```
Comment (paulodamaso) [inline src/test/java/org/jpeek/web/PagesTest.java]: @humb1t I think that we need to have an assertion here testing if the method was correctly performed OR testing if some exception was thrown

**Comment by humb1t** [comment]
https://github.com/llorllale/cactoos-matchers/issues/122

**Comment by paulodamaso** [comment]
@ilyakharlamov Do we have some resolution on this one?

**Comment by ilyakharlamov** [comment]
@paulodamaso Didn't get that. Which one?

**Comment by paulodamaso** [comment]
@ilyakharlamov Sorry, wrong recipient :D

**Comment by paulodamaso** [comment]
@humb1t Any resolution on this one?

**Comment by humb1t** [comment]
@paulodamaso no, will fix it tomorrow

File: src/test/java/org/jpeek/web/PagesTest.java (hunk 32 above)
Comment (humb1t) [reply src/test/java/org/jpeek/web/PagesTest.java]: @paulodamaso is it ok now?

File: src/test/java/org/jpeek/MainTest.java (hunk 31 above)
Comment (humb1t) [reply src/test/java/org/jpeek/MainTest.java]: I return true now

File: src/test/java/org/jpeek/MainTest.java (hunk 30 above)
Comment (humb1t) [reply src/test/java/org/jpeek/MainTest.java]: I return true now

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#321](https://github.com/yegor256/jpeek/issues/321); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#321](https://github.com/yegor256/jpeek/issues/321); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#321](https://github.com/yegor256/jpeek/issues/321); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@humb1t Ping

**Comment by humb1t** [comment]
@paulodamaso - hi, I missed the notification. Will fix it.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#321](https://github.com/yegor256/jpeek/issues/321); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
This pull request [#321](https://github.com/yegor256/jpeek/issues/321) is assigned to @nermeen78[/z](https://www.0crat.com/u/nermeen78), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/71366289-3fb9-498e-ba71-81ec38e774de); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@nermeen78[/z](https://www.0crat.com/u/nermeen78) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) everybody who has role `REV` is banned at [#321](https://github.com/yegor256/jpeek/issues/321); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#321` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#321](https://github.com/yegor256/jpeek/issues/321) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
